### ISSUE TITLE
No Widget´s shown in Widget Add Browser

### ISSUE THREAD

**Issue by cleicht** [brotkrueml/typo3-matomo-widgets#4] opened 2020-12-15 19:05 UTC
After updating to 0.3.0 on TYPO3 10.4.11 no Matomo Widgets a displayed in the + Widget Browser. So its not working

**Comment by brotkrueml** [comment] 2020-12-17 17:00
As version 0.3 is a major update with breaking changes, please read the migration guide:
https://docs.typo3.org/p/brotkrueml/typo3-matomo-widgets/0.3/en-us/Migration/Index.html

Please also mind, that after the update or changes on the configuration you have to flush the cache in the Admin Tools > Maintenance module. If you have more than one site configuration, the configuration adjustments have to be done manually.

**Comment by cleicht** [comment] 2020-12-17 18:10
No, Sorry. I have cleared any Chache and delete all typo3temp Files. There are no matomo-widgets in the Widgets Browser. Old displayed matomo-widgets in the dashboard are gone. 


TYPO3-Version
10.4.11
Webserver
Apache
PHP-Version
7.4.6
Datenbank (Default)
MySQL 5.7.30
Anwendungskontext
Production
Betriebssystem
Linux 4.19.56-x86_64-jb1
Letzter Lauf des Planer
17-12-20 um 19:00, Dauer 0 Min, (gestartet automatisch)

**Comment by brotkrueml** [comment] 2020-12-17 19:18
Have you executed the migration wizards as outlined in the manual? Do you have one or more than one site configuration? The settings moved to the site configuration.

**Comment by brotkrueml** [comment] 2020-12-20 08:29
Okay, first check, if the old extension configuration is still in LocalConfiguration.php (matomo_widgets). If yes, the migration wasn't done.

If you have only one site configuration, you can use the migration wizard. If not, add the configuration from LocalConfiguration.php manually into the appropriate site configuration (Tab "Matomo Widgets"). Then run the other migration wizards to adjust the dashboard widget identifiers and the access rights.

**Comment by brotkrueml** [comment] 2021-01-09 14:04
@cleicht Is this issue solved for you or not? If yes, please close it, if not, please reply so we can find the cause. If I here nothing from you in the next two weeks the issue will be closed.

**Comment by brotkrueml** [comment] 2021-01-10 19:04
@cleicht If you use a classic  (non-composer) installation of TYPO3 there is a bug. The site configuration is not read correctly.

**Comment by brotkrueml** [comment] 2021-04-11 07:39
Due to no response, this issue is closed.

**Closed by brotkrueml** 2021-04-11 07:39 UTC
Labels: question
